### ISSUE TITLE
Idea: Allow authorization with token which has permissions to GD WR component

### ISSUE THREAD

**Issue by ujovlado** [keboola/gooddata-provisioning#46]
Momentalne sa da autorizovat len s tokenom ktory je "master" (modry label v UI).

Davalo by mi zmysel, keby sa dalo autorizovat s tokenom, ktory ma prava na komponentu `keboola.gooddata-writer`.

T.j. token, ktory ma:

```js
{
  isMasterToken: false,
  componentAccess: ["keboola.gooddata-writer"],
  ...
}
```

Vyriesilo by to problem, kedy chce niekto ovladat provisioning zvonku, no nechce dat access do celeho projektu.

Nevyhoda: bol by to pristup k vsetkych writerom v projekte.

**Comment by JakubMatejka** [comment]
No moc ne, Provisioning nemá s Writerem a jeho konfiguracema vlastně nic společnýho. Ten název komponenty u tokenu se někde validuje? Že bychom tam dali gooddata-provisioning, nebo tak něco. Já akorát z toho 'admin' field v tokenu něco beru a ukládám, ale to by mohlo jít upravit.

**Comment by JakubMatejka** [comment]
Nó, tý jo, ale na `admin.id` je navázaný sso userů do projektu a já teď nedokážu úplně říct jestli to půjde předělat na id tokenu

**Comment by ujovlado** [comment]
Nie, to sa nevaliduje, pokial viem.

Mozeme to spravit tak, ze:

- regneme komponentu `keboola.gooddata-provisioning`
- a manualne ju pridame do "token editora" aby sla vybrat.

Nieco podobme sme pridavali pre orchestrator: https://github.com/keboola/kbc-ui/pull/1902

**Comment by ujovlado** [comment]
Pardon, validuje sa to. https://keboola.docs.apiary.io/#reference/tokens-and-permissions/tokens-collection/create-token (museli by sme ju vytvorit)

**Comment by JakubMatejka** [comment]
@kacurez nenapadá tě takhle z hlavy jestli by byl nějakej problém kdybysme GD uživatele pro sso nesestavovali z `admin.id` v tokenu, ale jen z `id` (kvůli tomu, aby nebyl potřeba master token)? Napadá mě tak akorát, že když si uživatel v ui refreshne token, tak by to vytvořilo druhýho GD usera a musel by se znovu přidat do projektu, ale to snad ničemu neva. (A to samý pro uživatele, kteří už někdy sso v novým Writeru použili)

**Comment by kacurez** [comment]
hmm ziadny vyslovene blocker ma nenapada, ale uplne do toho nevidim tak sa skor skusim "debilne" opytat na paru veci:  

1. cislovanie id tokenov je unikatne v ramci projektu takze je mozne ze po upravne 2 rozny kbc useri budu mat pristup do vzajomnych gooddata projektov pretoze maju rovnake `id` tokenu, alebo sa to este prefixuje `id` projektu?
2. Teraz v kazdom prihlaseni do gooddata cez sso vidim vsetky svoje gooddata projekty aj z ostatnych kbc projektoch/provisioningoch, takze by som po uprave na `id` videl vzdy len jeden gd projekt? (to asi nevadi)
3. Nebolo by lepsie "iba" fallbackovat na `id` tokenu? Teda defaultne brat `admin.id` a ak to neni master token tak fallbackovat na `component-access=="gooddata-provisioning"` + `token.id`?

**Comment by JakubMatejka** [comment]
ad 2) to už od prosince neplatí ani ve starým Writeru (http://status.keboola.com/security-enhancements-to-gooddata-projects-access)

ad 1) a 3) Ten fallback by vlastně šel. Teď se sestavuje id uživatele v GD z id projektu a id admina, tak id admina zaměním za id tokenu a přidám k němu nějaký příznak (aby nekolidovaly idčka adminů a tokenů) a mělo by to být ok(?)

**Comment by JakubMatejka** [comment]
jdu to teda upravit na ten fallback

**Comment by JakubMatejka** [comment]
viz. https://github.com/keboola/gooddata-provisioning/pull/47
Komponenta `keboola.gooddata-provisioning` už tam dokonce je (původně tam měl být worker pro async joby, ale nakonec se nevyužil)

**Comment by kacurez** [comment]
ui tu komponentu nezobrazuje pri zakladani token, input component access, tak to este pripravim

**Comment by JakubMatejka** [comment]
fixed by https://github.com/keboola/gooddata-provisioning/pull/47
