### ISSUE TITLE
Role readOnlyRole was not found in project

### ISSUE THREAD

**Issue by Halama** [keboola/gooddata-provisioning#48]
Trying to use KBC GoodData Provisioning API, more specifically `Add user to project` (https://keboolagooddataprovisioning.docs.apiary.io/#reference/0/users/add-user-to-a-project),  and assign `readOnly` role. However, when I try that, I receive `Role readOnlyRole was not found in project`. So I tried again with `readOnlyRole` and received `Parameter role must be one of: admin, editor, readOnly, dashboardOnly, keboolaEditorPlus`.

Ref: https://keboola.zendesk.com/agent/tickets/10387

**Comment by JakubMatejka** [comment]
fixed by https://github.com/keboola/gooddata-provisioning/pull/49
